inputs_def:
  - handle: cerebro
    json_schema:
      contentMediaType: oomol/var
  - handle: strategy
    json_schema:
      enum:
        - MeanReversion
        - DualMA
        - GridTradingStrategy
        - BollingerBandsStrategy
        - RsiMacdStrategy
      ui:options:
        labels:
          - MeanReversion
          - DualMA
          - GridTradingStrategy
          - BollingerBandsStrategy
          - RsiMacdStrategy
    value: MeanReversion
outputs_def:
  - handle: cerebro
    description: Output
    json_schema:
      contentMediaType: oomol/var
ui:
  default_width: 510.63671875
executor:
  name: python
  options:
    spawn: false
    entry: __init__.py
title: Add Strategy
icon: ":twemoji:brain:"
