inputs_def:
  - handle: cerebro
    description: Input
    json_schema:
      contentMediaType: oomol/var
  - handle: cash
    json_schema:
      type: number
outputs_def:
  []
ui:
  default_width: 450
executor:
  name: python
  options:
    spawn: false
    entry: __init__.py
title: Strategy Profit
icon: ":twemoji:dollar-banknote:"
