inputs_def:
  - handle: ticker
    description: Input
    json_schema:
      type: string
  - handle: start_time
    json_schema:
      type: string
      format: date-time
  - handle: end_time
    json_schema:
      type: string
      format: date-time
outputs_def:
  - handle: df
    description: Output
    json_schema:
      contentMediaType: oomol/var
ui:
  default_width: 450
executor:
  name: python
  options:
    spawn: false
    entry: __init__.py
title: Get Ticker
icon: ":logos:python:"
